// frontend/src/pages/Schedules.tsx
import { useEffect, useState } from 'react'

const API = (path: string) => `${import.meta.env.VITE_API_BASE ?? 'http://localhost:8000'}/api${path}`

type Schedule = {
  id: number
  post_id: number
  status: string
  scheduled_at: string
  attempt_count: number
}

export default function Schedules() {
  const [rows, setRows] = useState<Schedule[]>([])
  const [busy, setBusy] = useState(false)

  const load = async () => {
    setBusy(true)
    try {
      const res = await fetch(API('/schedules'))
      const json = await res.json()
      setRows(json)
    } catch (e) {
      console.error(e)
      alert('Failed to load schedules')
    } finally {
      setBusy(false)
    }
  }

  useEffect(() => {
    load()
    const t = setInterval(load, 5000)
    return () => clearInterval(t)
  }, [])

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h2 className="text-base font-semibold">Schedules</h2>
        <button onClick={load} disabled={busy} className="px-3 py-2 bg-gray-800 text-white rounded disabled:opacity-50">Refresh</button>
      </div>
      <div className="bg-white border rounded overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead>
            <tr className="bg-gray-50 text-gray-700">
              <th className="text-left p-2 border-b">ID</th>
              <th className="text-left p-2 border-b">Post</th>
              <th className="text-left p-2 border-b">Status</th>
              <th className="text-left p-2 border-b">Scheduled</th>
              <th className="text-left p-2 border-b">Attempts</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(r => (
              <tr key={r.id} className="odd:bg-white even:bg-gray-50">
                <td className="p-2 border-b">{r.id}</td>
                <td className="p-2 border-b">{r.post_id}</td>
                <td className="p-2 border-b">{r.status}</td>
                <td className="p-2 border-b">{new Date(r.scheduled_at).toLocaleString()}</td>
                <td className="p-2 border-b">{r.attempt_count}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// frontend/src/app/pages/schedules/schedules.component.ts
import { Component, signal, inject, ChangeDetectionStrategy, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { firstValueFrom } from 'rxjs';
import { ApiService, Schedule } from '../../services/api.service';

@Component({
  selector: 'app-schedules',
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="space-y-3">
      <div class="flex items-center justify-between">
        <h2 class="text-base font-semibold">Schedules</h2>
        <button 
          (click)="load()" 
          [disabled]="busy()" 
          class="px-3 py-2 bg-gray-800 text-white rounded disabled:opacity-50">
          Refresh
        </button>
      </div>
      <div class="bg-white border rounded overflow-x-auto">
        <table class="min-w-full text-sm">
          <thead>
            <tr class="bg-gray-50 text-gray-700">
              <th class="text-left p-2 border-b">ID</th>
              <th class="text-left p-2 border-b">Post</th>
              <th class="text-left p-2 border-b">Status</th>
              <th class="text-left p-2 border-b">Scheduled</th>
              <th class="text-left p-2 border-b">Attempts</th>
            </tr>
          </thead>
          <tbody>
            @for (row of rows(); track row.id) {
              <tr [class]="$even ? 'bg-gray-50' : 'bg-white'">
                <td class="p-2 border-b">{{ row.id }}</td>
                <td class="p-2 border-b">{{ row.post_id }}</td>
                <td class="p-2 border-b">{{ row.status }}</td>
                <td class="p-2 border-b">{{ formatDate(row.scheduled_at) }}</td>
                <td class="p-2 border-b">{{ row.attempt_count }}</td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class SchedulesComponent implements OnInit, OnDestroy {
  private apiService = inject(ApiService);
  private intervalId?: number;

  rows = signal<Schedule[]>([]);
  busy = signal(false);

  ngOnInit() {
    this.load();
    if (typeof window !== 'undefined') {
      this.intervalId = window.setInterval(() => this.load(), 5000);
    }
  }

  ngOnDestroy() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  async load() {
    this.busy.set(true);
    try {
      const result = await firstValueFrom(this.apiService.getSchedules());
      if (result) {
        this.rows.set(result);
      }
    } catch (e) {
      console.error(e);
      alert('Failed to load schedules');
    } finally {
      this.busy.set(false);
    }
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleString();
  }
}
