// frontend/src/app/pages/compose/compose.component.ts
import { Component, signal, computed, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { ApiService, Media } from '../../services/api.service';

@Component({
  selector: 'app-compose',
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="space-y-8">
      <section class="space-y-3">
        <h2 class="text-base font-semibold">Compose</h2>
        <textarea
          class="w-full border rounded p-3 focus:outline-none focus:ring"
          rows="4"
          placeholder="Write your post..."
          [value]="text()"
          (input)="text.set($any($event.target).value)"
        ></textarea>
        <div class="flex gap-2">
          <button 
            (click)="makeVariants()" 
            [disabled]="busy() || !text()" 
            class="px-3 py-2 bg-blue-600 text-white rounded disabled:opacity-50">
            Generate variants
          </button>
          <button 
            (click)="createPost()" 
            [disabled]="busy() || !text()" 
            class="px-3 py-2 bg-green-600 text-white rounded disabled:opacity-50">
            Create post
          </button>
          <button 
            (click)="publishNow()" 
            [disabled]="busy() || !postId()" 
            class="px-3 py-2 bg-purple-600 text-white rounded disabled:opacity-50">
            Publish now
          </button>
          <button 
            (click)="schedule()" 
            [disabled]="busy() || !postId()" 
            class="px-3 py-2 bg-amber-600 text-white rounded disabled:opacity-50">
            Schedule
          </button>
        </div>
        @if (variants().length > 0) {
          <div class="bg-white border rounded p-3">
            <h3 class="font-medium mb-2">Variants</h3>
            <ul class="list-disc pl-5 space-y-1">
              @for (variant of variants(); track $index) {
                <li>
                  <button 
                    class="text-blue-600 hover:underline" 
                    (click)="text.set(variant)">
                    {{ variant }}
                  </button>
                </li>
              }
            </ul>
          </div>
        }
      </section>

      <section class="space-y-3">
        <h2 class="text-base font-semibold">Media</h2>
        <input 
          type="file" 
          multiple 
          accept="image/*" 
          (change)="onFiles($event)"
          #fileInput
        />
        @if (files().length > 0) {
          <div class="space-y-2">
            @for (file of files(); track $index; let idx = $index) {
              <div class="flex items-center gap-2 text-sm">
                <div class="text-gray-600">{{ file.name }}</div>
                <input 
                  #altInput
                  class="border rounded p-1 flex-1" 
                  placeholder="Alt text (optional)"
                  [value]="altTexts()[idx]"
                  (input)="updateAltText(idx, $any($event.target).value)"
                />
              </div>
            }
            <button 
              (click)="uploadAll()" 
              [disabled]="busy() || !canUpload()" 
              class="px-3 py-2 bg-gray-800 text-white rounded disabled:opacity-50">
              Upload
            </button>
          </div>
        }
        @if (media().length > 0) {
          <div class="bg-white border rounded p-3">
            <h3 class="font-medium mb-2">Attached</h3>
            <ul class="list-disc pl-5 text-sm space-y-1">
              @for (m of media(); track m.id) {
                <li>
                  {{ m.filename }} 
                  @if (m.alt_text) {
                    (alt: {{ m.alt_text }})
                  }
                </li>
              }
            </ul>
          </div>
        }
      </section>
    </div>
  `
})
export class ComposeComponent {
  private apiService = inject(ApiService);

  text = signal('');
  files = signal<File[]>([]);
  altTexts = signal<string[]>([]);
  media = signal<Media[]>([]);
  busy = signal(false);
  variants = signal<string[]>([]);
  postId = signal<number | null>(null);
  scheduleId = signal<number | null>(null);

  canUpload = computed(() => this.files().length > 0);

  onFiles(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files) {
      this.files.set(Array.from(input.files));
      this.altTexts.set(new Array(input.files.length).fill(''));
    }
  }

  updateAltText(index: number, value: string) {
    const altTexts = [...this.altTexts()];
    altTexts[index] = value;
    this.altTexts.set(altTexts);
  }

  async uploadAll() {
    if (this.files().length === 0) return;
    this.busy.set(true);
    try {
      const uploaded: Media[] = [];
      for (let i = 0; i < this.files().length; i++) {
        const file = this.files()[i];
        const altText = this.altTexts()[i];
        const result = await firstValueFrom(this.apiService.uploadMedia(file, altText || undefined));
        if (result) {
          uploaded.push(result);
        }
      }
      this.media.update(prev => [...prev, ...uploaded]);
      this.files.set([]);
      this.altTexts.set([]);
    } catch (e) {
      console.error(e);
      alert('Upload failed');
    } finally {
      this.busy.set(false);
    }
  }

  async makeVariants() {
    this.busy.set(true);
    try {
      const result = await firstValueFrom(this.apiService.generateVariants(this.text()));
      if (result) {
        this.variants.set(result.variants ?? []);
      }
    } catch (e) {
      console.error(e);
      alert('Variant generation failed');
    } finally {
      this.busy.set(false);
    }
  }

  async createPost() {
    this.busy.set(true);
    try {
      const result = await firstValueFrom(this.apiService.createPost(
        this.text(),
        this.media().map(m => m.id)
      ));
      if (result) {
        this.postId.set(result.id);
        alert('Post created');
      }
    } catch (e) {
      console.error(e);
      alert('Post creation failed');
    } finally {
      this.busy.set(false);
    }
  }

  async publishNow() {
    const postId = this.postId();
    if (!postId) {
      alert('Create a post first');
      return;
    }
    this.busy.set(true);
    try {
      const result = await firstValueFrom(this.apiService.publishNow(postId));
      if (result) {
        alert(`Published with status: ${result.status}`);
      }
    } catch (e) {
      console.error(e);
      alert('Publish failed');
    } finally {
      this.busy.set(false);
    }
  }

  async schedule() {
    const postId = this.postId();
    if (!postId) {
      alert('Create a post first');
      return;
    }
    this.busy.set(true);
    try {
      const result = await firstValueFrom(this.apiService.schedulePost(postId));
      if (result) {
        this.scheduleId.set(result.id);
        alert('Scheduled');
      }
    } catch (e) {
      console.error(e);
      alert('Schedule failed');
    } finally {
      this.busy.set(false);
    }
  }
}

// frontend/src/pages/Compose.tsx
import { useEffect, useMemo, useRef, useState } from 'react'

const API = (path: string) => `${import.meta.env.VITE_API_BASE ?? 'http://localhost:8000'}/api${path}`

type Media = { id: number; filename: string; alt_text?: string }

export default function Compose() {
  const [text, setText] = useState('')
  const [files, setFiles] = useState<FileList | null>(null)
  const [media, setMedia] = useState<Media[]>([])
  const [busy, setBusy] = useState(false)
  const [variants, setVariants] = useState<string[]>([])
  const [postId, setPostId] = useState<number | null>(null)
  const [scheduleId, setScheduleId] = useState<number | null>(null)
  const altInputs = useRef<HTMLInputElement[]>([])

  const canUpload = useMemo(() => files && files.length > 0, [files])

  const onFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFiles(e.target.files)
  }

  const uploadAll = async () => {
    if (!files) return
    setBusy(true)
    try {
      const uploaded: Media[] = []
      for (let i = 0; i < files.length; i++) {
        const f = files[i]
        const fd = new FormData()
        fd.append('file', f)
        const alt = altInputs.current[i]?.value
        if (alt) fd.append('alt_text', alt)
        const res = await fetch(API('/media'), { method: 'POST', body: fd })
        if (!res.ok) throw new Error('upload_failed')
        const json = await res.json()
        uploaded.push(json)
      }
      setMedia(prev => [...prev, ...uploaded])
      setFiles(null)
    } catch (e) {
      console.error(e)
      alert('Upload failed')
    } finally {
      setBusy(false)
    }
  }

  const makeVariants = async () => {
    setBusy(true)
    try {
      const res = await fetch(API('/ai/variants'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: text })
      })
      const json = await res.json()
      setVariants(json.variants ?? [])
    } catch (e) {
      console.error(e)
      alert('Variant generation failed')
    } finally {
      setBusy(false)
    }
  }

  const createPost = async () => {
    setBusy(true)
    try {
      const res = await fetch(API('/posts'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, media_ids: media.map(m => m.id) })
      })
      if (!res.ok) throw new Error('post_failed')
      const json = await res.json()
      setPostId(json.id)
      alert('Post created')
    } catch (e) {
      console.error(e)
      alert('Post creation failed')
    } finally {
      setBusy(false)
    }
  }

  const publishNow = async () => {
    if (!postId) return alert('Create a post first')
    setBusy(true)
    try {
      const res = await fetch(API('/providers/default/publish'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ post_id: postId })
      })
      const json = await res.json()
      alert(`Published with status: ${json.status}`)
    } catch (e) {
      console.error(e)
      alert('Publish failed')
    } finally {
      setBusy(false)
    }
  }

  const schedule = async () => {
    if (!postId) return alert('Create a post first')
    setBusy(true)
    try {
      const res = await fetch(API('/schedules'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ post_id: postId })
      })
      const json = await res.json()
      setScheduleId(json.id)
      alert('Scheduled')
    } catch (e) {
      console.error(e)
      alert('Schedule failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="space-y-8">
      <section className="space-y-3">
        <h2 className="text-base font-semibold">Compose</h2>
        <textarea
          className="w-full border rounded p-3 focus:outline-none focus:ring"
          rows={4}
          placeholder="Write your post..."
          value={text}
          onChange={e => setText(e.target.value)}
        />
        <div className="flex gap-2">
          <button onClick={makeVariants} disabled={busy || !text} className="px-3 py-2 bg-blue-600 text-white rounded disabled:opacity-50">Generate variants</button>
          <button onClick={createPost} disabled={busy || !text} className="px-3 py-2 bg-green-600 text-white rounded disabled:opacity-50">Create post</button>
          <button onClick={publishNow} disabled={busy || !postId} className="px-3 py-2 bg-purple-600 text-white rounded disabled:opacity-50">Publish now</button>
          <button onClick={schedule} disabled={busy || !postId} className="px-3 py-2 bg-amber-600 text-white rounded disabled:opacity-50">Schedule</button>
        </div>
        {variants.length > 0 && (
          <div className="bg-white border rounded p-3">
            <h3 className="font-medium mb-2">Variants</h3>
            <ul className="list-disc pl-5 space-y-1">
              {variants.map((v, i) => (
                <li key={i}>
                  <button className="text-blue-600 hover:underline" onClick={() => setText(v)}>{v}</button>
                </li>
              ))}
            </ul>
          </div>
        )}
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">Media</h2>
        <input type="file" multiple accept="image/*" onChange={onFiles} />
        {files && files.length > 0 && (
          <div className="space-y-2">
            {Array.from(files).map((f, idx) => (
              <div key={idx} className="flex items-center gap-2 text-sm">
                <div className="text-gray-600">{f.name}</div>
                <input ref={el => { if (el) altInputs.current[idx] = el }} className="border rounded p-1 flex-1" placeholder="Alt text (optional)" />
              </div>
            ))}
            <button onClick={uploadAll} disabled={busy || !canUpload} className="px-3 py-2 bg-gray-800 text-white rounded disabled:opacity-50">Upload</button>
          </div>
        )}
        {media.length > 0 && (
          <div className="bg-white border rounded p-3">
            <h3 className="font-medium mb-2">Attached</h3>
            <ul className="list-disc pl-5 text-sm space-y-1">
              {media.map(m => (
                <li key={m.id}>{m.filename} {m.alt_text ? `(alt: ${m.alt_text})` : ''}</li>
              ))}
            </ul>
          </div>
        )}
      </section>
    </div>
  )
}
